### ISSUE TITLE
[BUG] [1.5b] (Fixed, could use some more testing) New icons in Learning Mode do not show Individual or Crate Menu

### ISSUE THREAD

**Issue by DarthKitty8** [tehruttiger/Stockpiler#49]
![](https://cdn.discordapp.com/attachments/1046273535854792806/1135704414699667587/image.png)

**Comment by DarthKitty8** [comment]
Should be fixed

**Comment by DarthKitty8** [comment]
Could use some more testing though.

**Comment by NotMeyi** [comment]
Hey, still having this issue on 1.51b ! I dont know what is causing it, but here are the logs : 
![image](https://github.com/tehruttiger/Stockpiler/assets/104357631/5a64bffc-29aa-4180-9843-7b5fa72775de)
